apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwsdb-api-deployment
  labels:
    app: nwsdb-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nwsdb-api
  template:
    metadata:
      labels:
        app: nwsdb-api
    spec:
      containers:
      - name: nwsdb-api
        image: nwsdb-core-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: BankApiUrl
          value: "http://bank-api:8080/"
---
apiVersion: v1
kind: Service
metadata:
  name: nwsdb-api
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: nwsdb-api
